name: Generate artifact name
description: Generate a pleasing artifact name that matches the workflow & run

branding:
  icon: archive
  color: green

inputs:
  repo-root:
    description: Where a checkout of the repository exists
    required: false
  repo-name:
    description: Pretty name for the project/repository
    required: false
  overrides:
    description: Override names for certain workflows
    required: false

runs:
  using: node20
  main: dist/index.js
