on:
  push:
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
